apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-app
  namespace: converter
  labels:
    app: converter-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: converter-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: converter-app
    spec:
      containers:
        - name: converter-app
          image: ghcr.io/kajal-nerkar/platomics-converter:latest
          imagePullPolicy: Always        # always pull latest from ghcr.io
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"