apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: converter-ingress
  namespace: converter
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: converter.local        # add "127.0.0.1 converter.local" to your hosts file
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: converter-service
                port:
                  number: 80